### ISSUE TITLE
Server restart losses

### ISSUE THREAD

**Issue by WingedZilla** [IvanMMM/ArmA3_Wasteland.Altis#2]
When the most recent server restart happened i lost these following things:
-Garage
-armed hunter
-Boom gate
-2 ramps (high) and 2 ramps
-industrial she (big)
Also a bunch of my walls around my base spawned wrong and i had to replace them
P.S. I'm in no way complaining. I love this server soooo much. I just wanted to bug report

**Comment by IvanMMM** [comment]
Losing objects is more like ingame bug. What about database rollbacks - yes, we are working on it to prevent objects losses in future.

**Comment by IvanMMM** [comment]
Moved to new server. Fixed.
