### ISSUE TITLE
Game falling to save at point of logout.

### ISSUE THREAD

**Issue by boundothis** [IvanMMM/ArmA3_Wasteland.Altis#6]
I've been backtracked several times now. Each time i logged out, I came back into game in a place i was at 15 minutes or more before hand. All items on person and vehicle are lost that i did not have at the time the game puts me back into. Both times the vehicles had been vendor bought and locked before logging out.

**Comment by IvanMMM** [comment]
Fixed in 58eeb11839b1d1b578b4730b84fd9a490d0cb689
